# Generated by Django 2.1.3 on 2018-12-20 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('matricule', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField()),
                ('lieuNaiss', models.CharField(max_length=50)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('login', models.CharField(max_length=50)),
                ('motPasse', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeFiliere', models.IntegerField()),
                ('filiere', models.CharField(choices=[('GEO', 'Géographe'), ('HIS', 'Histoire'), ('INF', 'Informatique'), ('MAT', 'Mathématiques'), ('DRT', 'Droit'), ('LIT', 'Littérature et Langue')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
                ('abbreviation', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPeriode', models.IntegerField()),
                ('dateDebut', models.DateField()),
                ('dateFin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeSemestre', models.IntegerField()),
                ('nomSemestre', models.CharField(choices=[('S1', 'Semestre 1'), ('S2', 'Semestre 2'), ('S3', 'Semestre 3'), ('S4', 'Semestre 4'), ('S5', 'Semestre 5'), ('S6', 'Semestre 6')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='SujetEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idSuejet', models.IntegerField()),
                ('nomSujet', models.CharField(max_length=50)),
                ('session', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Ue',
            fields=[
                ('codeUE', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nomUE', models.CharField(max_length=50)),
            ],
        ),
    ]
